---
- name: create users
  user:
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    group: sudo
    shell: "{{ item.shell }}"
    state: "{{ item.state }}"
    remove: "{{ (item.state == 'absent') | ternary('yes', 'no') }}"
  with_items: "{{ users }}"

- name: add user authorized keys
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ item.key }}"
    manage_dir: yes # create and manage permissions of .ssh directory
    state: "{{ item.state }}"
  with_items: "{{ users }}"
  when: "item.state == 'present'"