---
- name: install pip
  apt: 
    name: python-pip 
    state: latest

- name: work around docker-py
  pip:
    executable=/usr/bin/pip
    name=docker-py
    state=present
    version=1.8.1

- name: "install docker dependency : apt-transport-https"
  apt:
    name: apt-transport-https
    state: latest

- name: "install docker dependency : ca-certificates"
  apt:
    name: ca-certificates
    state: latest

- name: install docker key
  apt_key:
    keyserver: hkp://ha.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present

- name: install docker repository
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-xenial main
    state: present

- name: install docker engine
  apt:
    name: docker-engine
    state: present

- name: disable iptables for docker
  copy:
    src: docker-daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0600
  notify:
    - restart docker