version: '3'
services:
  postgres-db:
    container_name: database
    image: pgracio/dhis2-db:2.27-sierra-leone
    restart: unless-stopped
    environment:
      POSTGRES_USER: dhis
      POSTGRES_DB: dhis
      POSTGRES_PASSWORD: dhis
      POSTGRES_DB_TARGET: dhis-target
      PG_DATA: /var/lib/postgresql/data/pgdata:z
    volumes:
      - postgres-data-sierra-leone:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h database -p 5432 -d dhis2"]
      interval: 30s
      timeout: 30s
      retries: 150

volumes:
  postgres-data-sierra-leone: