---
- name: create mysql volume directory
  file: path=/opt/openmrs-mysql state=directory

- name: install mysql in docker
  docker_container:
    name: mysql-5.6
    image: mysql:5.6
    state: started
    pull: yes
    restart_policy: unless-stopped
    env:
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_DATABASE: "openmrs"
      MYSQL_USER: "openmrs"
      MYSQL_PASSWORD: "openmrs"
    volumes:
      - "/opt/openmrs-mysql:/var/lib/mysql"
    networks:
      - name: "{{ docker_network }}"