version: '3'

networks:
  epts:

volumes:
  mysql-data:

services:
  mysql-db:
    container_name: mysql-db
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_DATABASE: "openmrs"
      MYSQL_USER: "openmrs"
      MYSQL_PASSWORD: "openmrs"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - epts

  openmrs:
    container_name: openmrs
    build:
      context: ./openmrs
      args:
        DB_HOST: "mysql-db"
        DB_DATABASE: "openmrs"
        DB_USERNAME: "openmrs"
        DB_PASSWORD: "openmrs"
        DB_AUTO_UPDATE: 'true'
    image: openmrs-epts:1.0
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    networks:
      - epts

